[package]

name = "rpasha"
description = "Restrictive Precise Angle Shadowcasting, a field of view algorithm for a discrete playing field."
version = "0.0.1"
authors = ["bluss"]
license = "MIT/Apache-2.0"

[lib]

name = "rpasha"
path = "src/shadowcasting.rs"
